version: '3.1'
services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - '127.0.0.1:5000:80'    # Localhost only
      - '127.0.0.1:25:25'      # Localhost only
      - '127.0.0.1:143:143'    # Localhost only